name: EnderChest
version: 0.1.0
api: 1.0.0
author: Leon1917141
depend:
  - FakeInventories
main: EnderChest.Main
permissions:
  enderchest.see:
    default: true
  enderchest.see.other:
    default: false